# Generated by Django 4.2.7 on 2026-02-12 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_system', '0002_patient_user_alter_patient_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='image',
            field=models.ImageField(blank=True, help_text='Department image or AI-generated picture', null=True, upload_to='departments/'),
        ),
    ]
